services:
  - type: web
    plan: free
    name: WD-fileshare-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    repo: https://github.com/sputnicklu/test.git
    branch: main
    autoDeploy: false
    envVars:
      - key: ADMINS
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: DATABASE_URI
        sync: false
      - key: FSUB_UPDATE_LINK
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: REQ_CHANNEL
        sync: false